### ISSUE TITLE
Markers not showing up as greyed out.

### ISSUE THREAD

**Issue by Wolfie713** [TechnicJelle/BlueMapDeathMarkers#2]
Updated the main BlueMap plugin, and the offline markers are fully colored as though the players are online vs being greyed out.

**Comment by TechnicJelle** [comment]
This is the repository for BlueMap Death Markers, not BlueMap Offline Markers.
Please create your issue there: https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/issues.
Or, if possible, I think we could get this sorted much faster via Discord. The contact details for that are in the readme.

**Comment by Wolfie713** [comment]
Oops.

lol

🤦‍♂️


https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/issues/42
